name = "GradientMethods"
uuid = "823845fe-9a97-4ead-ad7d-52628efea333"
authors = ["s-valent <valent.shinkarev@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
